### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Mikanoshi** [Walibeiro/TChromeTabs32#1]
- [dcc32 Error] ChromeTabs32Classes.pas(3443): E2010 Incompatible types: 'TPoint' and 'TArrayOfPoint'
https://github.com/Walibeiro/TChromeTabs32/blob/master/Lib/ChromeTabs32Classes.pas#L3443
- Cannot open ChromeTabs32_DX101.groupproj, it says dproj files cannot be located.
- GDIPlus units are still referenced in some dpks

**Comment by Walibeiro** [comment]
Should be resolved now.
